from distutils.core import setup
setup(name='SpacePython',
    version='1.1.0',
    description='Skeleton for SpacePython implementation',
    requires=['yaml'],
    author='Space Domain Task Force (https://www.omg.org/solm/index.htm), Brad Kizzort',
    author_email='space@omg.org, bkizzort@harris.com',
    packages=['space'],
    data_files=[('data', ['data/SpacePythonDataset.yaml'])],
    scripts=['scripts/SetMomentumWheelSpeed.py', 
             'scripts/PassSetup.py',
             'scripts/ConfigureFEP.py'],
    license='LICENSE.txt',
    long_description=open('README.txt').read(),
    )
